export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
export const SELECTMENU = 'SELECTMENU'
export const SELECTTEAM = 'SELECTTEAM'
export const CREATETEAM = 'CREATETEAM'

export const SETEXPLORETALKDATA = 'ETEXPLORETALKDATA'
export const REMOVEEXPLORETALKDATA = 'REMOVEEXPLORETALKDATA'

export const SELECTEXPLORETALKDATA = 'SELECTEXPLORETALKDATA'
export const DESELECTEXPLORETALKDATA = 'DESELECTEXPLORETALKDATA'


